image: docker-hub.squiz.net/hosting/snabb-docker:latest

# Upload private key to runner
before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SNABB_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa

# Remove private key just in case
after_script:
  - rm ~/.ssh/id_rsa

stages:
 - build
 - test
 - deploy

build:
  stage: build
  tags:
    - "centos"
    - "7"
  script: 
    - make -j
  artifacts:
    paths:
      - src/snabb
    name: "release-$CI_COMMIT_REF_NAME"
    expire_in: 5 days
  
  # Cache luajit build
  cache:
    paths:
     - "lib/luajit/**/*.o"
     
test:
  stage: test
  tags:
    - "centos"
    - "7"
  script:
    - make -j
    - cd src
    - make test
  artifacts:
    paths:
      - src/testlog/*
    name: "testlogs-$CI_COMMIT_REF_NAME"
    expire_in: 1 days
    
  # Cache luajit build
  cache:
    paths:
     - "lib/luajit/**/*.o"

deploy:dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - "centos"
    - "7"
  dependencies:
    - build

  script:
    - for HOST in $SNABB_HOSTS; do rsync -arvze "ssh -o StrictHostKeychecking=no" src/snabb root@$HOST:/$SNABB_PATH; ssh $HOST systemctl restart snabb; done;

# Trigger deployment of config 
config:dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - "centos"
    - "7"
  dependencies:
    - build
  script:
    - "curl -X POST -F token=${SNABB_CONFIG_BUILD_TOKEN} -F ref=${CI_COMMIT_REF_NAME} https://gitlab.squiz.net/api/v4/projects/${SNABB_CONFIG_BUILD_REPO}/trigger/pipeline"
  retry: 2 # Curl back to gitlab can sometimes fail, retry
