image: docker-hub.squiz.net/hosting/snabb:latest

stages:
 - build
 - test

build:
  stage: build
  tags:
    - "centos"
    - "7"
  script: 
    - make -j
  artifacts:
    paths:
      - src/snabb
  
  # Cache luajit build
  cache:
    paths:
     - "snabb/lib/luajit/**/*.o"
     
test:
  stage: test
  tags:
    - "centos"
    - "7"
  script:
    - make -j
    - cd src
    - make test




