    local bit_lshift = require('bit').lshift
    local z = {}

    z.CMD_INTERFACE_ADD = 1
    z.CMD_INTERFACE_DELETE = 2
    z.CMD_INTERFACE_ADDRESS_ADD = 3
    z.CMD_INTERFACE_ADDRESS_DELETE = 4
    z.CMD_INTERFACE_UP = 5
    z.CMD_INTERFACE_DOWN = 6
    z.CMD_IPV4_ROUTE_ADD = 7
    z.CMD_IPV4_ROUTE_DELETE = 8
    z.CMD_IPV6_ROUTE_ADD = 9
    z.CMD_IPV6_ROUTE_DELETE = 10
    z.CMD_REDISTRIBUTE_ADD = 11
    z.CMD_REDISTRIBUTE_DELETE = 12
    z.CMD_REDISTRIBUTE_DEFAULT_ADD = 13
    z.CMD_REDISTRIBUTE_DEFAULT_DELETE = 14
    z.CMD_IPV4_NEXTHOP_LOOKUP = 15
    z.CMD_IPV6_NEXTHOP_LOOKUP = 16
    z.CMD_IPV4_IMPORT_LOOKUP = 17
    z.CMD_IPV6_IMPORT_LOOKUP = 18
    z.CMD_INTERFACE_RENAME = 19
    z.CMD_ROUTER_ID_ADD = 20
    z.CMD_ROUTER_ID_DELETE = 21
    z.CMD_ROUTER_ID_UPDATE = 22
    z.CMD_HELLO = 23
    z.CMD_IPV4_NEXTHOP_LOOKUP_MRIB = 24
    z.CMD_VRF_UNREGISTER = 25
    z.CMD_INTERFACE_LINK_PARAMS = 26
    z.CMD_NEXTHOP_REGISTER = 27
    z.CMD_NEXTHOP_UNREGISTER = 28
    z.CMD_NEXTHOP_UPDATE = 29
    z.CMD_MESSAGE_MAX = 30

    -- Zebra route types
    z.ROUTE_SYSTEM = 0
    z.ROUTE_KERNEL = 1
    z.ROUTE_CONNECT = 2
    z.ROUTE_STATIC = 3
    z.ROUTE_RIP = 4
    z.ROUTE_RIPNG = 5
    z.ROUTE_OSPF = 6
    z.ROUTE_OSPF6 = 7
    z.ROUTE_ISIS = 8
    z.ROUTE_BGP = 9
    z.ROUTE_PIM = 10
    z.ROUTE_HSLS = 11
    z.ROUTE_OLSR = 12
    z.ROUTE_BABEL = 13
    z.ROUTE_MAX = 14

-- Zebra message flags
z.FLAG_INTERNAL = 0x01
z.FLAG_SELFROUTE = 0x02
z.FLAG_BLACKHOLE = 0x04
z.FLAG_IBGP = 0x08
z.FLAG_SELECTED = 0x10
z.FLAG_FIB_OVERRIDE = 0x20
z.FLAG_STATIC = 0x40
z.FLAG_REJECT = 0x80

-- Zebra nexthop flags
z.NEXTHOP_IFINDEX = 1
z.NEXTHOP_IFNAME = 2
z.NEXTHOP_IPV4 = 3
z.NEXTHOP_IPV4_IFINDEX = 4
z.NEXTHOP_IPV4_IFNAME = 5
z.NEXTHOP_IPV6 = 6
z.NEXTHOP_IPV6_IFINDEX = 7
z.NEXTHOP_IPV6_IFNAME = 8
z.NEXTHOP_BLACKHOLE = 9


-- Constants in quagga/lib/zclient.h

-- Zebra API message flags
z.ZAPI_MESSAGE_NEXTHOP = 0x01
z.ZAPI_MESSAGE_IFINDEX = 0x02
z.ZAPI_MESSAGE_DISTANCE = 0x04
z.ZAPI_MESSAGE_METRIC = 0x08
z.ZAPI_MESSAGE_MTU = 0x10
z.ZAPI_MESSAGE_TAG = 0x20

z.INTERFACE_NAMSIZE = 20
z.INTERFACE_HWADDR_MAX = 20

z.INTERFACE_ACTIVE = bit_lshift(1, 0)
z.INTERFACE_SUB = bit_lshift(1, 1)
z.INTERFACE_LINKDETECTION = bit_lshift(1, 2)

-- Zebra link layer types
z.LLT_UNKNOWN = 0
z.LLT_ETHER = 1
z.LLT_EETHER = 2
z.LLT_AX25 = 3
z.LLT_PRONET = 4
z.LLT_IEEE802 = 5
z.LLT_ARCNET = 6
z.LLT_APPLETLK = 7
z.LLT_DLCI = 8
z.LLT_ATM = 9
z.LLT_METRICOM = 10
z.LLT_IEEE1394 = 11
z.LLT_EUI64 = 12
z.LLT_INFINIBAND = 13
z.LLT_SLIP = 14
z.LLT_CSLIP = 15
z.LLT_SLIP6 = 16
z.LLT_CSLIP6 = 17
z.LLT_RSRVD = 18
z.LLT_ADAPT = 19
z.LLT_ROSE = 20
z.LLT_X25 = 21
z.LLT_PPP = 22
z.LLT_CHDLC = 23
z.LLT_LAPB = 24
z.LLT_RAWHDLC = 25
z.LLT_IPIP = 26
z.LLT_IPIP6 = 27
z.LLT_FRAD = 28
z.LLT_SKIP = 29
z.LLT_LOOPBACK = 30
z.LLT_LOCALTLK = 31
z.LLT_FDDI = 32
z.LLT_SIT = 33
z.LLT_IPDDP = 34
z.LLT_IPGRE = 35
z.LLT_IP6GRE = 36
z.LLT_PIMREG = 37
z.LLT_HIPPI = 38
z.LLT_ECONET = 39
z.LLT_IRDA = 40
z.LLT_FCPP = 41
z.LLT_FCAL = 42
z.LLT_FCPL = 43
z.LLT_FCFABRIC = 44
z.LLT_IEEE802_TR = 45
z.LLT_IEEE80211 = 46
z.LLT_IEEE80211_RADIOTAP = 47
z.LLT_IEEE802154 = 48
z.LLT_IEEE802154_PHY = 49

-- "non-official" architectural constants
z.MAX_CLASS_TYPE = 8

for k,v in pairs(z) do
    local s_d = k:find('_')
    if s_d ~= nil then
	local s_int = k:sub(0, s_d-1)
	local s_var = k:sub(s_d+1)
	if not z[s_int] then
	    z[s_int] = {}
	end
	z[s_int][v] = s_var
    end
end

return z
